# Generated by Django 5.0.7 on 2024-07-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='published',
        ),
    ]
