# Generated by Django 5.0.7 on 2024-07-20 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('important', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('background_image_path', models.ImageField(blank=True, null=True, upload_to='tour-packs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelApp.place')),
            ],
        ),
        migrations.CreateModel(
            name='PackInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tour_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelApp.tourpack')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='tour_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelApp.tourtype'),
        ),
    ]
