# Generated by Django 5.0.7 on 2024-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
