# Generated by Django 5.0.7 on 2024-07-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0002_article_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='articles_count',
            new_name='articles_amount',
        ),
    ]
