# Generated by Django 5.0.7 on 2024-07-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUsApp', '0002_lid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='email',
        ),
    ]
