# Generated by Django 5.0.7 on 2024-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUsApp', '0003_remove_discussion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
